apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wevote-apps
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: wevote-infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/wevote
  prune: true
  wait: true
  timeout: 10m
