apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-scan-script
  namespace: registry
data:
  scan-all.sh: |
    #!/bin/sh
    set -e
    
    # Install required tools (show errors this time)
    echo "Installing curl, jq, and trivy..."
    apk add --no-cache curl jq wget || {
        echo "ERROR: Failed to install tools"
        exit 1
    }
    
    # Install Trivy
    echo "Downloading Trivy..."
    wget -qO- https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin || {
        echo "ERROR: Failed to install Trivy"
        exit 1
    }
    
    # Verify tools are installed
    which curl jq trivy || {
        echo "ERROR: Tools not found in PATH"
        exit 1
    }
    
    REGISTRY="192.168.2.200:30500"
    REGISTRY_USER="admin"
    REPORT_DIR="/reports"
    TIMESTAMP=$(date +%Y%m%d-%H%M%S)
    
    # Ensure reports directory is readable
    chmod 755 ${REPORT_DIR} || true
    
    echo "Starting registry scan at $(date)"
    
    # Get list of repositories
    REPOS=$(curl -u ${REGISTRY_USER}:${REGISTRY_PASSWORD} \
      http://${REGISTRY}/v2/_catalog | jq -r '.repositories[]')
    
    # Create report file
    REPORT_FILE="${REPORT_DIR}/scan-${TIMESTAMP}.txt"
    echo "Registry Vulnerability Scan Report - $(date)" > ${REPORT_FILE}
    echo "==========================================" >> ${REPORT_FILE}
    echo "" >> ${REPORT_FILE}
    
    # Scan each repository
    for repo in ${REPOS}; do
      echo "Scanning ${repo}..." | tee -a ${REPORT_FILE}
      
      # Get tags
      TAGS=$(curl -u ${REGISTRY_USER}:${REGISTRY_PASSWORD} \
        http://${REGISTRY}/v2/${repo}/tags/list | jq -r '.tags[]' 2>/dev/null || echo "latest")
      
      for tag in ${TAGS}; do
        IMAGE="${REGISTRY}/${repo}:${tag}"
        echo "  Scanning ${IMAGE}..." | tee -a ${REPORT_FILE}
        
        # Scan with Trivy
        trivy image --quiet --severity HIGH,CRITICAL \
          --username ${REGISTRY_USER} \
          --password ${REGISTRY_PASSWORD} \
          ${IMAGE} >> ${REPORT_FILE} 2>&1 || true
        
        echo "" >> ${REPORT_FILE}
      done
    done
    
    echo "" >> ${REPORT_FILE}
    echo "Scan completed at $(date)" >> ${REPORT_FILE}
    
    # Make report readable by all
    chmod 644 ${REPORT_FILE}
    
    # Print summary
    echo ""
    echo "=== Scan Summary ==="
    grep -E "Total:|CRITICAL|HIGH" ${REPORT_FILE} || echo "No HIGH/CRITICAL vulnerabilities found!"
    
    # Keep only last 30 days of reports
    find ${REPORT_DIR} -name "scan-*.txt" -mtime +30 -delete 2>/dev/null || true
    
    echo "Report saved to: ${REPORT_FILE}"
